CREATE VIEW Employee_Contact 
SELECT 
  DATE() as "Current Date",
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  PHONE_NUMBER,
  ADDRESS,
  ZIP_CODE
FROM EMPLOYEE
INNER JOIN CONTACT_INFO
ON EMPLOYEE.ID = CONTACT_INFO.ID;
