CREATE VIEW Employee_Contact AS
SELECT 
    DATE() AS "Current Date",
    EMPLOYEE.FIRST_NAME,
    EMPLOYEE.LAST_NAME,
    CONTACT_INFO.EMAIL,
    CONTACT_INFO.PHONE_NUMBER,
    CONTACT_INFO.ADDRESS,
    CONTACT_INFO.ZIP_CODE
FROM EMPLOYEE
INNER JOIN CONTACT_INFO
ON EMPLOYEE.ID = CONTACT_INFO.ID;
